admin_complextag_index:
    path:     /
    defaults: { _controller: "AppBundle:ComplexTag:index" }
    methods:  GET

admin_complextag_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ComplexTag:show" }
    methods:  GET

admin_complextag_new:
    path:     /new
    defaults: { _controller: "AppBundle:ComplexTag:new" }
    methods:  [GET, POST]

admin_complextag_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ComplexTag:edit" }
    methods:  [GET, POST]

admin_complextag_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ComplexTag:delete" }
    methods:  DELETE
